name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - uses: actions/checkout@v3
      - run: go test -mod vendor ./...
